repos:
  - repo: local
    hooks:
    - id: sq-black
      name: sq-black
      language: system
      entry: sqblack/cli.py
      args:
        - -l 100
      types: [python]
      exclude: (versioneer.py|sqblack/_version.py)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v2.0.0
    hooks:
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: trailing-whitespace   # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending     # Replaces or checks mixed line ending.
        args: [--fix=lf]
      - id: end-of-file-fixer     # Makes sure files end in a newline and only a newline.
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: check-ast             # Simply check whether files parse as valid python.
